In [1]:
import numpy as np

#### 1. Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

#### Ответ
a) $A \cdot B$ и $B \cdot A$ не определены, поскольку матрицы одинаковые и число столбцов в любой из них не совпадает с числом строк в другой

б) $A \cdot B$ определена, поскольку число столбцов у $A(5)$ совпадает с числом строк у $B(5)$, итоговая матрица будет размером $2 \times 3$

в) $A\cdot B = (8\times 8)$, $B\cdot A = (3\times3)$

г) $A\cdot B = B\cdot A = (4\times 4)$

#### 2. Найти сумму и произведение матриц
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

#### Ответ
$A + B = \begin{pmatrix}5 & -3\\3 & 5\end{pmatrix}$

$A\cdot B = \begin{pmatrix}4 & -11\\12 & -3\end{pmatrix}$


In [10]:
a = np.array([[1, -2],
              [3, 0]])

b = np.array([[4, -1],
              [0, 5]])
print(f'A + B = \n{a + b}')
print(f'A * B = \n{a.dot(b)}')

A + B = 
[[ 5 -3]
 [ 3  5]]
A * B = 
[[  4 -11]
 [ 12  -3]]


#### 3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3𝐴−2𝐵+4𝐶  для матриц
$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A - 2B + 4C = 
\begin{pmatrix}3 & 21\\ 9 & -18 \end{pmatrix} - 
\begin{pmatrix}0 & 10\\ 4 & -2 \end{pmatrix} + 
\begin{pmatrix}8 & -32\\ 4 & 4 \end{pmatrix} = 
\begin{pmatrix}11 & -5\\ 9 & -12 \end{pmatrix}$

In [11]:
a = np.array([[1, 7],
              [3, -6]])

b = np.array([[0, 5],
              [2, -1]])

c = np.array([[2, -4],
              [1, 1]])

print(f'3𝐴−2𝐵+4𝐶 = \n {3*a - 2*b + 4*c}')

3𝐴−2𝐵+4𝐶 = 
 [[ 11  -5]
 [  9 -12]]


#### 4. Вычислить  $𝐴𝐴^T$  и  $𝐴^T𝐴$
$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.

$A^T = \begin{pmatrix} 
4 & 5 & 2\\
1 & -2 & 3
\end{pmatrix}
$

$A\cdot A^T = \begin{pmatrix}
17 & 18 & 11\\
18 & 29 & 4\\
11 & 4 & 13 \end{pmatrix}
$

$A^T\cdot{A} = \begin{pmatrix}
45 & 0\\
0 & 14
\end{pmatrix}
$

In [25]:
a = np.array([[4, 1],
              [5, -2], 
              [2, 3]])

a_t = a.T
print(f'a * a_t = \n {a.dot(a_t)}')
print(f'a_t * a  = \n {a_t.dot(a)}')

a * a_t = 
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
a_t * a  = 
 [[45  0]
 [ 0 14]]
