In [7]:
import numpy as np
from scipy.linalg import lu

#### 1. Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

#### Решение
a) $$x_1 = \frac{
\begin{vmatrix}
1&-2\\
7&-4\end{vmatrix}
}{
\begin{vmatrix}
1&-2\\
3&-4\end{vmatrix}
} = \frac{10}{2} = 5$$

$$x_2 = \frac{
\begin{vmatrix}
1&1\\
3&7\end{vmatrix}
}{
\begin{vmatrix}
1&-2\\
3&-4\end{vmatrix}
} = \frac{4}{2} = 2$$

б) $$x_1 = \frac{
\begin{vmatrix}
10&-1&5\\
-2&1&-3\\
1&4&1
\end{vmatrix}
}{
\begin{vmatrix}
2&-1&5\\
1&1&-3\\
2&4&1
\end{vmatrix}
} = \frac{86}{43} = 2$$

$$x_2 = \frac{
\begin{vmatrix}
2&10&5\\
1&-2&-3\\
2&1&1
\end{vmatrix}
}{
\begin{vmatrix}
2&-1&5\\
1&1&-3\\
2&4&1
\end{vmatrix}
} = -\frac{43}{43} = -1$$

$$x_2 = \frac{
\begin{vmatrix}
2&-1&10\\
1&1&-2\\
2&4&1
\end{vmatrix}
}{
\begin{vmatrix}
2&-1&5\\
1&1&-3\\
2&4&1
\end{vmatrix}
} = \frac{43}{43} = 1$$

In [8]:
A = np.array([
    [2,-1,5],
    [1,1,-3],
    [2,4,1]
])
v = np.array([10,-2,1])
np.linalg.solve(A,v)

array([ 2., -1.,  1.])

#### 2*. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

#### Решение
a) $V = \begin{pmatrix}
1&0&0\\
2&1&0\\
3&4&1
\end{pmatrix}$

б) $V = \begin{pmatrix}
1&0&0&0\\
2&1&0&0\\
3&5&1&0\\
4&6&7&0
\end{pmatrix}$

#### 3*. Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

#### Решение
$U=\begin{pmatrix}
2&1&3\\
11&7&5\\
9&8&4
\end{pmatrix} \rightarrow
\begin{pmatrix}
2&1&3\\
0&1.5&-11.5\\
0&0&16.95
\end{pmatrix}$

$L = \begin{pmatrix}
1&0&0\\
5.5&1&1\\
4.5&2.3&1
\end{pmatrix}$

$Ly = b \rightarrow y = \begin{pmatrix}1\\-11.5\\16.95\end{pmatrix}$

$Ux=y \rightarrow x=\begin{pmatrix}-1\\0\\1\end{pmatrix}$



In [9]:
A = np.array([[ 2.  ,  1.  ,  3.  ],
       [11.  ,  7.  ,  5.  ],
       [ 9.  ,  8,  4.  ]])
A.dot(np.array([-1,0,1]))

array([ 1., -6., -5.])

#### 4*. Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$L = \begin{pmatrix}
9&0&0\\
-5&5&0\\
5&2&3
\end{pmatrix};
L^T = \begin{pmatrix}
9&-5&5\\
0&5&2\\
0&0&3
\end{pmatrix}
$

$Ly=b \rightarrow y=\begin{pmatrix}59\\-33\\-12\end{pmatrix}$

$L^Tx=y \rightarrow x=\begin{pmatrix}6\\-5\\-4\end{pmatrix}$

In [10]:
L = np.array([
    [9,0,0],
    [-5,5,0],
    [5,2,3]
])
b = np.array([531, -460, 193])

In [11]:
y = np.linalg.inv(L).dot(b)
y

array([ 59., -33., -12.])

In [12]:
x = np.linalg.inv(L.T).dot(y)
x

array([ 6., -5., -4.])